### ISSUE TITLE
ModuleNotFoundError: No module named 'pcapy'

### ISSUE THREAD

**Issue by zzq1016** [michaelsaxon/velodyne-dataset-utils#1]
thank you for releasing code.
when i run parser.py, an error occurs: "ModuleNotFoundError: No module named 'pcapy'".
where can i get this module?
@michaelsaxon

**Comment by michaelsaxon** [comment]
You should be able to install it via
`pip install pcapy`

**Comment by zzq1016** [comment]
ok. That worked. Thanks!
